pipeline {
    agent {
        node {
            label 'master'
        }
    }
    
    stages {
        stage('Clone') {
            steps {
                git (
                    url: 'https://github.com/YogeshMCA/Dev.git',
                    credentialsId:'994dba1c-cabc-4d5f-b9d3-8c72366daefb',
                    branch : 'master'                    
                )
                
            }
        }
    
    stage('Build') {
            steps {
                bat 'mvn package'
                }
            }
     }
        
    post {
        success {
            echo 'Deployment Completed Successfully'
        }
        failure {
            echo 'Deployment Failed'
        }
 }
}
