pipeline {
    agent {
        node {
            label 'master'
        }
    }
    
    stages {
        stage('Clone') {
            steps {
                git (
                    url: 'https://github.com/YogeshMCA/Currency-Conversion-Service---Pivotal.git',
                    credentialsId:'994dba1c-cabc-4d5f-b9d3-8c72366daefb',
                    branch : 'master'                    
                )
                
            }
        }
    
    stage('Build') {
            steps {
                bat 'mvn package'
                }
            }
     stage('Deployment') {
            steps {
                pushToCloudFoundry(
                            target: 'api.run.pivotal.io',
                            organization: 'Microservices-Samples',
                            cloudSpace: 'development',
                            credentialsId: 'PCF_LOGIN'
                            )
                }
            }
     }
        
    post {
        success {
            echo 'Deployment Completed Successfully'
        }
        failure {
            echo 'Deployment Failed'
        }
 }
}
